config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :managers
  
  root 'products#index'
  get  'render_article' => 'ajax#render_article'
  post  'add_to_cart' => 'ajax#add_to_cart'

  post "pay2go_return"   => 'orders#pay2go_return'
  post "pay2go_notify"   => 'orders#pay2go_notify'
  post "pay2go_customer" => 'orders#pay2go_customer'

  
  post "spgateway_return"   => 'orders#spgateway_return'
  post "spgateway_notify"   => 'orders#spgateway_notify'
  post "spgateway_customer" => 'orders#spgateway_customer'

  namespace :manager do
    root to:  'core#index'
    get 'index' => 'core#index'
    get 'set_session' => 'core#set_session'
    get 'clear' => 'core#clear'
    get 'zbc' => "core#zbc"
    resources :products do
      member do
        post :off_shelf
        post :on_shelf
        post :replenish
        post :mark
        post :unmark
      end
    end    
    resources :orders do
      member do
        post :cancel
        post :shipped
        post :refund
        post :return
        post :return_fail
        get  :message_board
        get  :message_of_cancel
        post :create_message        
      end
    end
    resources :articles do
      member do
        post :sticky
        post :sticky_cancel
      end
    end    
    resources :settings
  end 

  resources :products do
    collection do
      get :total_articles
    end  
    member do 
      post :add_to_cart
    end
  end

  resources :categories, only: [:index, :show]

  resources :carts  do 
    collection do 
      get :checkout
      post :refresh
      delete :delete_cart_item
      delete :clean
    end
  end

  resources :orders  do 
    member do 
      post :realtime_return
      post :realtime_notify
      post :non_realtime_customer
      post :non_realtime_notify
      post :pay2go_cc_notify
      post :pay2go_cc_return
      post :pay2go_wa_notify
      post :pay2go_wa_return
      post :pay2go_atm_return
      post :pay2go_atm_notify
    end
  end   

  namespace :account do 
    get 'index' => 'core#index'
    get 'user_info' => 'core#user_info'
    post 'build_user_info' => 'core#build_user_info'
    resources :orders do 
      member do
        post :cancel
        post :request_return
        get  :message_board
        get  :message_of_cancel
        get  :message_of_return
        post :create_message
        get  :payment_info
      end
    end
  end

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
  	is_admin
  end       
         
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
	before_action :authenticate_user!

	def index
		@orders = current_user.orders.order(id: :DESC ).page(params[:page]).per(20)
	end


	def cancel
		@order = Order.find_by(id: params[:id])
		@comment = @order.comments.build(comment_params)
		if @comment.save
			@order.cancel
			flash[:success] = "訂單已取消"
			redirect_to order_path(@order.token)
		else	
			render :message_of_cancel
		end	
		rescue
			flash[:warning] = "取消訂單失敗，此訂單可能已經出貨"
			redirect_to order_path(@order.token)
	end

	def request_return
		@order = Order.find_by(id: params[:id])
		@comment = @order.comments.build(comment_params)
		if @comment.save
			@order.request_good_returned!
			flash[:success] = "已申請退貨"
			redirect_to order_path(@order.token)
		else
			render "message_of_return"
		end
		rescue
			flash[:warning] = "申請退貨失敗，請再試一次"
			redirect_to order_path(@order.token)			
	end

	# message board
	def message_board
		@order = Order.find_by(token: params[:id])
		@comments = @order.comments
		@comment = @order.comments.build

	end

	def create_message
		@order = Order.find_by(id: params[:id])
		@comments = @order.comments
		@comment = @order.comments.build(comment_params)

		if @comment.save
			redirect_to :back		
		else
			render :message_board
		end	
	end

	def message_of_cancel
		@order = Order.find_by(token: params[:id])
		@comment = @order.comments.build
	end

	def message_of_return
		@order = Order.find_by(token: params[:id])
		@comment = @order.comments.build		
	end

	#取號資訊
	def payment_info
		@order = Order.find_by(token: params[:id])
		@payment_info = @order.payment_info
	end

	private
		def comment_params
			params.require(:comment).permit(:title, :content, :user_name)
		end
end

app/controllers/manager/articles_controller.rb
class Manager::ArticlesController < ApplicationController

	def index
		@articles = Article.page(params[:page]).per(10).order(created_at: :DESC)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to root_path
		else
			render :new
		end		
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to manager_article_path(@article)
		else
		 render :edit
		end 		
	end

	def show
		@article = Article.find(params[:id])
	end


	def destroy
		@article = Article.find(params[:id])

		if @article.destroy

			flash[:success] = "#{@article.title} 已被刪除"
			redirect_to :back
		else
			render :index
		end	
	end	


	def sticky
		@article = Article.find_by(id: params[:id])

		position = params[:position].to_i
		now_sticky = Article.find_by(sticky: position)


		if now_sticky
			now_sticky.sticky = 0
			now_sticky.save
		end
		
		@article.sticky = position
		@article.save

		redirect_to :back			

	end

	def sticky_cancel
		@article = Article.find_by(id: params[:id])
		@article.sticky = 0
		@article.save
		redirect_to :back			
	end


	private

		def article_params
			params.require(:article).permit(:title, :description, :article_img)
		end

end

app/controllers/manager/core_controller.rb
class Manager::CoreController < ManagerController

	def index
		session[:query_days] ||= "30"
		session[:order]   ||= "DESC"
		ob = session[:order]
		interval = session[:query_days].to_i
		query_scope =  params["query_scope"] ? params["query_scope"] : "undone_orders"
		@orders = Order.last_days(interval).includes(:user).send(query_scope).order("created_at #{ob}").page(params[:page]).per(5)
	end

	def set_session
		array = ["p_order", "order_by", "order", "query_days"]
		array.each do |key|
			if params[key]
				session[key] = params[key]
			end
		end	

		redirect_to :back
	  rescue
	  	redirect_to manager_index_path
 	end

	def clear
		session.delete("query_days")
		redirect_to :back 
	end


	def zbc

		clnt = HTTPClient.new
		@a = clnt.get_content("https://capi.pay2go.com/API/QueryTradeInfo")
	end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ManagerController

	def index
		@orders = Order.includes(:user).order('id DESC').page(params[:page])
	end

	def show
		@order = Order.find(params[:id])
		@order_info = @order.info
		@order_items = @order.items
	end


	def shipped
		@order = Order.find_by(id: params[:id])
		@order.ship!
		redirect_to :back
		rescue
			flash[:warning] = "出貨動作失敗，此訂單可能已經被用戶取消！"
			redirect_to manager_order_path(@order)	
	end

	def cancel
		@order = Order.find_by(id: params[:id])
		@comment = @order.comments.build(comment_params)

		if @comment.save
			@order.cancel
			flash[:success] = "訂單已取消"
			redirect_to manager_order_path(@order)
		else
			render :message_of_cancel
		end	
	end

	def refund
		@order = Order.find_by(id: params[:id])
		@order.refund_completed!

		redirect_to :back
	end

	def return
		@order = Order.find_by(id: params[:id])
		@order.return_good!

		redirect_to :back
	end

	def return_fail
		@order = Order.find_by(id: params[:id])
		@order.return_fail!

		redirect_to :back		
	end

	# message board
	def message_board
		@order = Order.find_by(id: params[:id])
		@comments = @order.comments
		@comment = @order.comments.build

	end

	def create_message
		@order = Order.find_by(id: params[:id])
		@comments = @order.comments
		@comment = @order.comments.build(comment_params)

		if @comment.save
			redirect_to :back		
		else
			render :message_board
		end	
	end

	def message_of_cancel
		@order = Order.find_by(id: params[:id])
		@comment = @order.comments.build
	end

	private
		def comment_params
			params.require(:comment).permit(:title, :content, :user_name)
		end	
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController


	def index
		session[:p_order] ||= "DESC"
		session[:order_by] ||= "id"
		po = session[:p_order]
		ob = session[:order_by]
		query_scope =  params["query_scope"] ? params["query_scope"] : "all"
		@products = Product.includes(:photo).send(query_scope).order("#{ob} #{po}").page(params[:page]).per(10)
	end

	def new
		@product = Product.new
		@photo = @product.build_photo
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			redirect_to product_path(@product)
		else
			render :new
		end		
	end

	def edit
		@product = Product.find(params[:id])
		@photo = @product.photo || @product.build_photo
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to product_path(@product)
		else
		 render :edit
		end 	
	end

	def destroy
		@product = Product.find(params[:id])

		if @product.destroy

			flash[:success] = "#{@product.title} 已被刪除"
			redirect_to :back
		else
			render :index
		end	
	end

	def off_shelf
		@product = Product.find(params[:id])
		@product.off_shelf

		flash[:success] = "#{@product.title} 已下架"
		redirect_to :back
	end

	def on_shelf
		@product = Product.find(params[:id])
		@product.on_shelf

		flash[:success] = "#{@product.title} 已上架"
		redirect_to :back		
	end

	def replenish
		@product = Product.find_by(id: params[:id])
		@product.quantity += params[:number].to_i
		
		if @product.save
			flash[:success] = "#{@product.title}庫存數量增加 #{params[:number].to_i}，庫存變化 #{@product.quantity - params[:number].to_i} => #{@product.quantity} "

		  redirect_to :back
		end
		rescue
			flash[:warning] = "操作失敗，請重新嘗試，補貨數量請填入整數"  
			redirect_to :back
	end

	#商品置頂
	def mark
		if Product.be_marked.count < 5

			product = Product.find_by(id: params[:id])
			product.mark = true
			product.save
	
			flash[:success] = "#{product.title} 已置頂"
	
			redirect_to :back
		else
			flash[:warning] = "置頂數量已滿，請先將部分產品取消置頂"
			redirect_to :back
		end		
	end

	#取消置頂
	def unmark
		product = Product.find_by(id: params[:id])
		product.mark = false
		product.save

		flash[:success] = "#{product.title} 已取消置頂"

		redirect_to :back		
	end



	private

		def product_params
			params.require(:product).permit(:title, :description, :quantity, :price, :category_name,
																			 :category_id, :nutrition_facts, :certification, :origin,
																			 :introduction, :weight, :expiration_date, :special,
																			 :special_price, photo_attributes: [:image, :id])
		end

end

app/controllers/manager/settings_controller.rb
class Manager::SettingsController < ManagerController

	def index
		
	end

	def create
		if @setting.save
			redirect_to root_path(@setting)
		else
		 render :edit
		end 				
	end


	def edit
	end

	def update

		if @setting.update(setting_params)
			redirect_to manager_settings_path
		else
		 render :back
		end 		
	end

	private

		def setting_params
			params.require(:setting).permit(:carousel1, :carousel2, :carousel3, 
				:carousel1_link, :carousel2_link, :carousel3_link,
				:carousel1_p, :carousel2_p, :carousel3_p,
				:carousel1_link_p, :carousel2_link_p, :carousel3_link_p,
				:about_us, :q_and_a, :notice,
				:email, :line, :phone, :shipping_cost, :shipping_free)
		end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController

	before_action :authenticate_manager!
	before_action :admin_required


	def admin_required
		if	!current_manager.admin?
			redirect_to root_path
		end	
	end


end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/manager/articles_helper.rb
module Manager::ArticlesHelper
end

app/helpers/manager/core_helper.rb
module Manager::CoreHelper
	def manager_link(name, options, html_options = {})
		if manager_signed_in?
			link_to(name, options, html_options)
		end	
	end
end

app/helpers/manager/orders_helper.rb
module Manager::OrdersHelper
  def active_link(scope, name, options, html_options = {})
  	default_query_scope = scope if html_options[:default] 
    query_scope = request.query_parameters["query_scope"] ? request.query_parameters["query_scope"] : default_query_scope
    if  query_scope == scope
      content_tag(:span, name, class: "bold gray")
    else
      link_to(name, options, html_options)
    end   
  end	
end

app/helpers/manager/products_helper.rb
module Manager::ProductsHelper

	def render_shelf_option(product)
		if 	product.selling == true
			link_to("下架", off_shelf_manager_product_path(product), method: :post)
		else
			link_to("上架", on_shelf_manager_product_path(product), method: :post)
		end	
	end

end

app/helpers/manager/settings_helper.rb
module Manager::SettingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	#設定付款時限
	def set_expire_date(order, days)
		date = order.created_at.advance(days: days)
		date.to_s(:Ymd)
	end

	#將總秒數格式化
	def formatted_duration(total_seconds)
		hours = total_seconds / (3600)
		minutes = (total_seconds / 60) % 60
		seconds = total_seconds % 60
		"#{hours}#{minutes}#{seconds}"
	end
	
	#單項商品小計
	def order_item_sum(item)
		item.price * item.quantity
	end

	#商品總價
	def render_order_total_price(items)
		sum = 0
		items.each do |item|
			sum += order_item_sum(item)
		end
		sum	
	end


	#AASM翻譯
	def render_order_state(order)
		content_tag(:span, t("orders.order_state.#{order.aasm_state}"), class: "order-state #{order.aasm_state}")
	end

	def render_order_state_manager(order)
		content_tag(:span, t("orders.order_state_manager.#{order.aasm_state}"), class: "order-state #{order.aasm_state}")
	end	

	#已付款or未付款
	def render_order_paid_state(order)
		if order.is_paid?
			content_tag(:span, "已付款", class: "green")
		else
			content_tag(:span, "未付款", class: "red")
		end		
	end

	#付款方式翻譯
	def render_payment_method(method)
		I18n.t("payment_method.#{method}")
	end

	#顯示取號付款資訊
	def render_payment_info(info)
		if info["PaymentType"] == "CVS"
			render 'cvs_payment_info'
		elsif info["PaymentType"] == "VACC"
			render 'vacc_payment_info'
		end			
	end

	#是否顯示取號資訊連結
	def payment_info_link(order)
		if  order.aasm_state == "number_received"
			content_tag(:span, " | ") +
			link_to("察看繳費資訊", payment_info_account_order_path(@order.token))
		end
	end

	#超過繳費期限，訂單失效
	def dead?(order)
		order.deadline < DateTime.now && ( order.aasm_state == "number_received" || order.aasm_state == "order_placed" )
	end
end

app/views/manager/orders/_messages.html.erb
<div class="messages">

	<% if @comments.count == 0 %>
		<span>目前沒有留言</span>
	<% else %>	
	  <% @comments.each do |c| %>
	  	<% if c.persisted? %>
	  	  <div class="comment-body clearfix">
	  	  	<div>
	  	  		<%= render_comment_title(c) %>
	  	  	</div>
	  	  	<span class="large"><%= c.user_name %>： </span>
	  	  	<div class="comment-content"><%= simple_format(c.content) %></div>
	  	  	<span class="comment-time pull-right"><%= c.created_at.to_s(:normal) %></span>
	  	  </div>				
	  	  <hr class="hr-2">
	  	<% end %>
	  <% end %>
	<% end %>  
</div>

app/views/manager/orders/_state_option.html.erb
<div class="under-h2">
	<% case order.aasm_state %>
	<% when "order_placed" %>
		<%= link_to("取消訂單",
								message_of_cancel_manager_order_path(order),
								class: "btn-small") %>
	<% when "number_received" %>
		<%= link_to("取消訂單",
								message_of_cancel_manager_order_path(order),
								class: "btn-small") %>	
	<% when "paid" %>
		<%= link_to("出貨",
								shipped_manager_order_path(order),
								class: "btn-small", method: :post) %>	
		<%= link_to("取消訂單",
								message_of_cancel_manager_order_path(order),
								class: "btn-small") %>
	<% when "refund_processing" %>
		<%= link_to("通知買家退款完成",
								refund_manager_order_path(order),
								class: "btn-small", method: :post) %>						
	<% when "return_processing" %>
		<%= link_to("退貨",
				return_manager_order_path(order),
				class: "btn-small", method: :post, data: { confirm: "確定同意退貨？"}) %>
		<%= link_to("拒絕退貨",
				return_fail_manager_order_path(order),
				class: "btn-small", method: :post, data: { confirm: "確定拒絕退貨？"}) %>				
	<% when "shipped" %>
		<span class="label label-default">已出貨</span>				
	<% when "order_cancelled" %>
		<span class="label label-default">此訂單已被取消</span>
	<% when "payment_fail" %>
		<span class="label label-default">付款失敗</span>	
		<span class="red"><%= @order.trade_info["Message"] %></span>			
	<% when "good_returned" %>
		<span class="label label-default">退貨處理完成</span>
	<% when "good_return_failed" %>
		<span class="label label-default">不符合退貨條件</span>
	<% end %>
</div>

app/views/manager/orders/_state_query.html.erb
<%= form_tag "https://capi.pay2go.com/API/QueryTradeInfo", method: :post do  %>

  <%= hidden_field_tag "MerchantID",      Pay2go.merchant_id %>
  <%= hidden_field_tag "RespondType",     "JSON" %>
  <%= hidden_field_tag "Version",         "1.1" %>

  <%= hidden_field_tag "MerchantOrderNo", order.order_number %>
  <%= hidden_field_tag "TimeStamp",       order.created_at.to_i %>
  <%= hidden_field_tag "Amt",             order.total %>

  <%= hidden_field_tag "CheckValue",      Pay2goService.new(order).check("state_query") %>

  <%= submit_tag "查詢", class: "btn-small" %>
<% end %>

app/views/manager/orders/_trade_infos.html.erb
<table class="table table-striped table-bordered margin-0">
  <tbody>
    <tr>
      <td class="high-table bold">
        訂購人電子郵件
      </td>
    </tr>
    <tr>
      <td class="high-table">
        <%= order.user.email %>
      </td>
    </tr>
    <tr>
      <td class="high-table bold">
        訂單編號
      </td>
    </tr>
    <tr>
      <td class="high-table">
        <span class="monospace"><%= order.order_number %></span>
      </td>
    </tr>

    <% if order.is_paid %>
      <tr>
        <td class="high-table bold">
          付款方式
        </td>
      </tr>
      <tr>
        <td class="high-table">
          <%= render_payment_method(order.payment_method) %>
        </td>
      </tr>      
      <tr>
        <td class="high-table bold">
          付款時間
        </td>
      </tr>
      <tr>
        <td class="high-table">
          <%= order.trade_info["Result"]["PayTime"] %>
        </td>
      </tr>
      <tr>
        <td class="high-table bold">
          交易金額
        </td>
      </tr>
      <tr>
        <td class="high-table">
          <span class="small"> NTD </span> <%= order.trade_info["Result"]["Amt"] %>
        </td>
      </tr>                  
    <% end %>
  </tbody>
</table>

app/views/manager/orders/index.html.erb
    <h2>訂單列表 </h2>
    
    
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>訂單編號</th>
<!--           <th>聯繫買家</th>
 -->          <th class="hidden-xs">下單時間</th>
          <th width="80">收件人</th>
          <th class="hidden-xs">信箱</th>
          <th>訂單狀態</th>
          <th>查詢</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to(order.order_number, manager_order_path(order), class: "monospace" ) %> 
          </td>
<!--           <td><%= link_to "買賣留言板", message_board_manager_order_path(order) %></td>
 -->          <td class="hidden-xs"> <%= order.created_at.to_s(:normal) %> </td>
          <td> <%= order.user.info["shipping_name"] %></td>
          <td class="hidden-xs"><%= order.user.email %></td>
          <td> <%= render_order_state(order) %> </td>
          <td><%= render "state_query", order: order %></td>
        </tr>
        <% end %>
    
      </tbody>
    </table>
    <%= paginate @orders %>

app/views/manager/orders/message_board.html.erb
<%= render "common/error_messages", var: @comment %>
<div class="mt md">
	<h2>買賣留言板</h2>

	<%= render "messages" %>

	<div class="new-message">
		<h2>留言給買家</h2>
		
		<%= form_for([@order, @comment], {url: create_message_manager_order_path(@order),
		 method: :post })do |f| %>
		
			<%= f.hidden_field :user_name, value: "圓滿生機" %>

			<%= f.text_area :content, placeholder: "輸入新留言....", class: "new-message-area" %>

			<%= f.submit "送出", class: "btn-normal" %>
			<% end %>
	</div>
</div>

app/views/manager/orders/message_of_cancel.html.erb
<%= render "common/error_messages", var: @comment %>

<div class="new-message">
	<h2>取消訂單</h2>
	<%= form_for([@order, @comment], {url: cancel_manager_order_path(@order), method: :post})do |f| %>
	
	<%= f.hidden_field :title, value: "取消訂單" %>
	<%= f.hidden_field :user_name, value: "圓滿生機" %>

	<%= f.label :content, "請說明取消訂單原因" %>
	<%= f.text_area :content, class: "new-message-area"  %>

	<%= f.submit "取消訂單", class: "btn-normal", data: { confirm: "確定取消訂單？"} %>
	<% end %>
</div>

app/views/manager/orders/show.html.erb
<div class="checkout-order clearfix">
  <h2>
  	訂單明細
  	<span class="gray">(<%= t("orders.order_state_manager.#{@order.aasm_state}")%>)</span>
  </h2>

<!--   <%= link_to "買賣留言板", message_board_manager_order_path(@order), class: "under-h2" %>
 -->  
  <%= render "manager/orders/state_option", order: @order %>
  
  <%= render "orders/order_infos_table" %>

  <h2> 其他資訊 </h2>

  <%= render 'trade_infos', order: @order %>

</div>