config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :managers
  
  root 'products#index'
  get  'render_article' => 'ajax#render_article'
  post  'add_to_cart' => 'ajax#add_to_cart'

  post "pay2go_return"   => 'orders#pay2go_return'
  post "pay2go_notify"   => 'orders#pay2go_notify'
  post "pay2go_customer" => 'orders#pay2go_customer'

  
  post "spgateway_return"   => 'orders#spgateway_return'
  post "spgateway_notify"   => 'orders#spgateway_notify'
  post "spgateway_customer" => 'orders#spgateway_customer'

  namespace :manager do
    root to:  'core#index'
    get 'index' => 'core#index'
    get 'set_session' => 'core#set_session'
    get 'clear' => 'core#clear'
    get 'zbc' => "core#zbc"
    resources :products do
      member do
        post :off_shelf
        post :on_shelf
        post :replenish
        post :mark
        post :unmark
      end
    end    
    resources :orders do
      member do
        post :cancel
        post :shipped
        post :refund
        post :return
        post :return_fail
        get  :message_board
        get  :message_of_cancel
        post :create_message        
      end
    end
    resources :articles do
      member do
        post :sticky
        post :sticky_cancel
      end
    end    
    resources :settings
  end 

  resources :products do
    collection do
      get :total_articles
    end  
    member do 
      post :add_to_cart
    end
  end

  resources :categories, only: [:index, :show]

  resources :carts  do 
    collection do 
      get :checkout
      post :refresh
      delete :delete_cart_item
      delete :clean
    end
  end

  resources :orders  do 
    member do 
      post :realtime_return
      post :realtime_notify
      post :non_realtime_customer
      post :non_realtime_notify
      post :pay2go_cc_notify
      post :pay2go_cc_return
      post :pay2go_wa_notify
      post :pay2go_wa_return
      post :pay2go_atm_return
      post :pay2go_atm_notify
    end
  end   

  namespace :account do 
    get 'index' => 'core#index'
    get 'user_info' => 'core#user_info'
    post 'build_user_info' => 'core#build_user_info'
    resources :orders do 
      member do
        post :cancel
        post :request_return
        get  :message_board
        get  :message_of_cancel
        get  :message_of_return
        post :create_message
        get  :payment_info
      end
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items, source: :product


	def add_product_to_cart(product, quantity)
		quantity = quantity > 10 ? 10 : quantity 
		cart_item = self.cart_items.build
		cart_item.product = product
		cart_item.quantity = quantity
		cart_item.save
	end

	def quantity_plus(product, quantity)
		cart_item = self.cart_items.find_by(product_id: product.id)
		max_quantity = product.quantity > 10 ? 10 : product.quantity
		quantity = max_quantity - cart_item.quantity < quantity ? max_quantity - cart_item.quantity : quantity

		cart_item.quantity += quantity
		cart_item.save 
	end

	#已訂單快照計算購物車總價
	def total_price
		sum = 0

		self.items.each do |item|
			sum += item.price * item.quantity
		end
		
		sum	
	end

	#確認庫存，數量不足，或完全沒貨
	def stock_check
		@hash = {}
		d_array = []
		c_array = []

		self.cart_items.each do |item|
			product = Product.find_by(id: item.product_id)
			if item.quantity > product.quantity && product.quantity == 0
				item.destroy
				d_array <<  product.title
				@hash[:delete] = d_array		
			elsif item.quantity > product.quantity
				item.quantity = product.quantity
				item.save
				c_array << product.title
				@hash[:change] = c_array
			end
		end
		@hash
	end

	#清空購物車
	def clean!
		self.cart_items.destroy_all
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!, only: [:checkout]
	before_action :cart_items_to_hash, only: [:index, :checkout]

	def index
		@items = current_cart.items.includes(:photo)
	end

	def refresh
		cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
		cart_item.quantity = params[:quantity]
		cart_item.save

		redirect_to carts_path
	end

	def checkout
		if current_cart.items.count == 0
			flash[:warning] = "您的購物車內沒有商品"
			redirect_to root_path
		end	
		@user_info = current_user ? current_user.info : {}
		@order = current_user ? current_user.orders.build : Order.new
		@info = @order.build_info
	end

	def delete_cart_item
		cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
		cart_item.destroy

		flash[:notice] = "你已將 #{params[:product_title]} 從購物車刪除"
		redirect_to carts_path
	end

	def clean
		current_cart.clean!

		flash[:success] = "購物車已清空"
		redirect_to carts_path
	end

	private


end

app/helpers/carts_helper.rb
module CartsHelper

	def render_cart_items_count(cart)
		cart.items.count	
	end

	#購物車商品總價
	def render_cart_total_price(items, cart_items)
		@sum = 0
		items.each do |product|
			@sum += sum(cart_items, product)
		end
		@sum	
	end

	#試算運費
	def trial_shipping_cost
		@shipping_cost = @sum >= 1000 ? 0 : @setting.shipping_cost
		@shipping_cost 
	end	

	#訂單應付總金額
	def render_total_amount
		@sum + @shipping_cost
	end

	#購物車單件商品小計
	def sum(cart_items_hash, product)
		price = product.special? ? product.special_price : product.price
		price * find_cart_items_quantity(cart_items_hash, product)
	end

	def find_cart_items_quantity(cart_items_hash, product)
		cart_items_hash[product.id]
	end


	#有特價時顯示特價(購物車)
	def render_price_in_cart(product)
		if product.special?
			content_tag(:span, product.special_price, class: "red")
		else
			product.price
		end		
	end


end

app/views/carts/_cart_table.html.erb
<table class="cart-table table table-striped">
  <thead>
    <tr class="lighter small">
      <th class="th"><span class="visible-xs-inline">PRODUCT</span></th>
      <th class="th"><span class="hidden-xs ">PRODUCT</span></th>
      <th class="th ">PRICE</th>
      <th class="th ">AMOUNT</th>
    </tr>
  </thead>
  <tbody class="td-body">
    <% @items.each do |product| %>
      <tr class="visible-xs xs-tr">
        <td colspan="4">
         <h4 class="center"> 
          <%= link_to(product.title, product_path(product), class: "normal-link bold") %>
         </h4> 
        </td>
      </tr>
      <tr>
        <td class="td-image">
          <%= link_to delete_cart_item_carts_path(product_id: product.id, product_title: product.title), 
          method: :delete, class: "remove-cart-item" do %>
            <i class="fa fa-times" aria-hidden="true"></i>
          <% end %>  
          <%= image_tag(product.photo.image.thumb.url, class: "cart-image") %>
        </td>
        <td class="td-item-info">
          <!-- 特價提示 -->
          <% if product.special? %>
            <span class="smallest red block">
              <i class="fa fa-star-half-o" aria-hidden="true"></i>
              特價商品
            </span>
          <% end %>
          <!-- 特價提示end -->

          <%= link_to(product.title, product_path(product), class: "normal-link bold hidden-xs") %>
          <%= form_tag({ controller: "carts", action: "refresh"}, method: :post, remote: true) do %>
            <div class="lighter">

            	<span class="hidden-xs">數量 ： </span>
              <span> <span class="visible-xs-inline small gray">x</span>
                <%= select_tag(:quantity, options_for_select(product_quantity_range(product),
            	  find_cart_items_quantity(@cart_items_hash, product)),
                 onchange: "this.form.submit()") %>
              </span>  
					  </div>
					  <%= hidden_field_tag :product_id, product.id %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
					<% end %>  	
        </td>
        <td class="td-price ">
          <div class="inline-block small lighter mr <%= product.special? ? "red" : "gray" %>">$</div> 
          <div class="break-word inline-block">
            <%= render_price_in_cart(product) %>
          </div>
        </td>
        <td class="td-sum">
          <div class="inline-block small lighter mr gray">$</div>
          <div class="inline-block break-word"><%= sum(@cart_items_hash, product) %></div>
        </td>
      </tr>
    <% end %>
		<tr>
			<td colspan="4" class="cart-message">
  		  購物車內共有<span class="cart-items-count"><%= current_cart.items.count %></span>項商品，
  		  消費總金額 NT$ 
  		  <span class="cart-price-total"><%= render_cart_total_price(@items, @cart_items_hash) %></span><br>
        
        <span class="small red"><%= "單筆訂單滿#{@setting.shipping_free}免運" %></span class="small red">



        <div id="cart-bottom-botton" class="clearfix">
          <%= link_to products_path, class: "inline-block back hover-left btn-normal pull-left" do %>
            <div>
              <i class="fa fa-arrow-left" aria-hidden="true"></i>
              <span>繼續選購</span>
            </div>
          <% end %>
               
          <%= link_to checkout_carts_path, class: "inline-block hover-right btn-normal pull-right" do %>
            <div>
              <span class="">前往結帳</span>
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
            </div>  
          <% end %>
        </div>

  		</td>
		</tr>
  </tbody>
</table>

app/views/carts/checkout.html.erb
  <div class="checkout-order clearfix">

  	<h2> 購物明細 </h2>
		
		<div class="under-h2">
			<%= link_to "返回購物車", carts_path, class: "btn-small" %>
		</div>

		<table class="table table-striped checkout-order-table">
		  <thead>
		    <tr>
          <th class="high-table p-title">商品明細</th>
          <th class="high-table">單價</th>
          <th class="high-table">數量</th>
          <th class="high-table">小計</th>
        </tr>
		  </thead>
		  <tbody>
		    <% current_cart.items.each do |product| %>
		      <tr>
		        <td class="high-table p-title">
		          <%= link_to(product.title, product_path(product)) %>
		        </td>
		        <td class="high-table">
		        	<%= true_price(product) %>
		        </td>
		        <td class="high-table">
		        	<%= find_cart_items_quantity(@cart_items_hash, product) %>
		        </td>
		        <td class="high-table">
		          <span class="small">NTD</span>
			          <%=  true_price(product) * find_cart_items_quantity(@cart_items_hash, product) %>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>


		<div class="clearfix money-info">
      <div class="pull-right">
				<div class="money-box">
					<span class="money-type">商品總價</span>
					<span class="dollar-sign">$</span>
					<span class="money"><%= render_cart_total_price( current_cart.items, @cart_items_hash) %></span>
				</div>      	
				<div class="money-box">
					<span class="money-type">運費(郵寄/宅配)</span>
					<span class="dollar-sign">$</span>
					<span class="money"><%= trial_shipping_cost %></span>
				</div>	
				<div class="money-box border-top">
        	<span class="money-type">本次消費應付金額</span>
					<span class="dollar-sign">$</span>
        	<span class="money"><%= render_total_amount %></span>
        </div>	
      </div>
    </div>

		<hr>

		<h2>訂單資訊</h2>

		<div class="shipping-info-form">
			<%= simple_form_for @order do |f| %>
				<%= f.simple_fields_for :info do |info_form| %>
					<div class="checkout-form">
						<%= info_form.input :shipping_name, label: "收件人姓名",
						 input_html: { value:  @user_info["shipping_name"], class: "form-group"} %>
					</div>
					<div class="checkout-form">
						<%= info_form.input :postal_code, label: "郵遞區號",
						 input_html: { value:  @user_info["postal_code"], class: "form-group"} %>
					</div>					
					<div class="checkout-form">
						<%= info_form.input :shipping_address, label: "收件人地址",
						 input_html: { value:  @user_info["shipping_address"], class: "form-group"} %>
					</div>
					<div class="checkout-form">
						<%= info_form.input :phone_number, label: "聯絡電話",
						 input_html: { value:  @user_info["phone_number"], class: "form-group"} %>
					</div>
				<% end %>
				
					<%= f.submit "確認下單，前往付款", class: "btn-normal", data: { disable_with: "訂單送出中..."} %>
			<% end %>
		</div>	

</div>		

app/views/carts/index.html.erb
<div class="cart-page for-lg" style="margin-bottom: 60px;">
	<div class="row">
	<div class="mt col-md-offset-1 col-md-10 col-sm-12">
		<div class="center">
			<div class="cart-page-title">
				<h2 class="background">
					<span class="ur-cart">購物車
					<%= link_to "(清空購物車)", clean_carts_path, method: :delete,
				 	class: "small clean-cart", data: { confirm: "確定清空購物車？"} %>
				 </span>
				</h2> 	
			</div>
		</div>
  	
  	<%= render 'cart_table' %>


<!-- 		<div id="note">
			<span id="note-title">購物須知：</span>	<br>
			<div id="note-body">
				<span><i class="fa fa-caret-right" aria-hidden="true"></i> 每筆訂單需加收運費xx元整</span><br>
				<span><i class="fa fa-caret-right" aria-hidden="true"></i> 單筆訂單消費滿xx元可享運費全免</span><br>
				<span><i class="fa fa-caret-right" aria-hidden="true"></i> 運送地區僅限台澎金馬</span><br>
				<span>
					<i class="fa fa-caret-right" aria-hidden="true"></i>
					 更多訊息請詳見 - <%= link_to "關於本店", "#" %>
				</span>
			</div>
		</div> -->

		<hr>
	</div>
	</div>	
</div>