config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :managers
  
  root 'products#index'
  get  'render_article' => 'ajax#render_article'
  post  'add_to_cart' => 'ajax#add_to_cart'

  post "pay2go_return"   => 'orders#pay2go_return'
  post "pay2go_notify"   => 'orders#pay2go_notify'
  post "pay2go_customer" => 'orders#pay2go_customer'

  
  post "spgateway_return"   => 'orders#spgateway_return'
  post "spgateway_notify"   => 'orders#spgateway_notify'
  post "spgateway_customer" => 'orders#spgateway_customer'

  namespace :manager do
    root to:  'core#index'
    get 'index' => 'core#index'
    get 'set_session' => 'core#set_session'
    get 'clear' => 'core#clear'
    get 'zbc' => "core#zbc"
    resources :products do
      member do
        post :off_shelf
        post :on_shelf
        post :replenish
        post :mark
        post :unmark
      end
    end    
    resources :orders do
      member do
        post :cancel
        post :shipped
        post :refund
        post :return
        post :return_fail
        get  :message_board
        get  :message_of_cancel
        post :create_message        
      end
    end
    resources :articles do
      member do
        post :sticky
        post :sticky_cancel
      end
    end    
    resources :settings
  end 

  resources :products do
    collection do
      get :total_articles
    end  
    member do 
      post :add_to_cart
    end
  end

  resources :categories, only: [:index, :show]

  resources :carts  do 
    collection do 
      get :checkout
      post :refresh
      delete :delete_cart_item
      delete :clean
    end
  end

  resources :orders  do 
    member do 
      post :realtime_return
      post :realtime_notify
      post :non_realtime_customer
      post :non_realtime_notify
      post :pay2go_cc_notify
      post :pay2go_cc_return
      post :pay2go_wa_notify
      post :pay2go_wa_return
      post :pay2go_atm_return
      post :pay2go_atm_notify
    end
  end   

  namespace :account do 
    get 'index' => 'core#index'
    get 'user_info' => 'core#user_info'
    post 'build_user_info' => 'core#build_user_info'
    resources :orders do 
      member do
        post :cancel
        post :request_return
        get  :message_board
        get  :message_of_cancel
        get  :message_of_return
        post :create_message
        get  :payment_info
      end
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	mount_uploader :certification, CertificationUploader
	mount_uploader :nutrition_facts,  NutritionFactsUploader

	belongs_to :category
	has_one :photo, dependent: :destroy

	# validates_presence_of :photo

	accepts_nested_attributes_for :photo

	validates :title, presence: { message: "請填寫商品名稱" }
	validates :price, presence: { message: "請輸入商品價格" }
	validate :valid_special_price

	scope :products_are_selling, ->{ where(selling: true) }


	#上架的商品
	scope :selling, -> { where(selling: true) }
	#下架的商品
	scope :unselling, -> { where(selling: false)}
	#置頂的商品
	scope :be_marked, -> { where(mark: true) }
	#特價的商品
	scope :special_price, -> { where(special: true) }
	#缺貨的商品
	scope :out_of_stock, -> { where(quantity: 0) }


	attr_accessor :category_name

	before_save :find_or_create_category

	# 驗證特價時特價價格不能為空
	def valid_special_price
		if self.special && self.special_price.blank?
			errors.add(:special, "必須設定特價價格")
		end	
	end

	class << self 

		def set_inventory!(current_cart)
			current_cart.cart_items.each do |item|
				product = item.product
				product.quantity -= item.quantity
				product.save
			end	
		end
	end

	def off_shelf
		self.selling = false
		self.save
	end

	def on_shelf
		self.selling = true
		self.save		
	end

	#讓friendly_id能使用中文
	def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  #title重複時找price
  def slug_candidates
    [
      :title,
      [:title, :price]
    ]
  end

  def should_generate_new_friendly_id?
  	slug.blank? || title_changed? # slug 為 nil 或 name column 變更時更新
  end

	private
		def find_or_create_category
			if @category_name && !category_name.empty?
				category = Category.find_by(name: @category_name)
				if category.nil?
					self.create_category(name: @category_name)
				else
					self.category = category
				end
			end			
		end




end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController


	def index
		session[:p_order] ||= "DESC"
		session[:order_by] ||= "id"
		po = session[:p_order]
		ob = session[:order_by]
		query_scope =  params["query_scope"] ? params["query_scope"] : "all"
		@products = Product.includes(:photo).send(query_scope).order("#{ob} #{po}").page(params[:page]).per(10)
	end

	def new
		@product = Product.new
		@photo = @product.build_photo
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			redirect_to product_path(@product)
		else
			render :new
		end		
	end

	def edit
		@product = Product.find(params[:id])
		@photo = @product.photo || @product.build_photo
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to product_path(@product)
		else
		 render :edit
		end 	
	end

	def destroy
		@product = Product.find(params[:id])

		if @product.destroy

			flash[:success] = "#{@product.title} 已被刪除"
			redirect_to :back
		else
			render :index
		end	
	end

	def off_shelf
		@product = Product.find(params[:id])
		@product.off_shelf

		flash[:success] = "#{@product.title} 已下架"
		redirect_to :back
	end

	def on_shelf
		@product = Product.find(params[:id])
		@product.on_shelf

		flash[:success] = "#{@product.title} 已上架"
		redirect_to :back		
	end

	def replenish
		@product = Product.find_by(id: params[:id])
		@product.quantity += params[:number].to_i
		
		if @product.save
			flash[:success] = "#{@product.title}庫存數量增加 #{params[:number].to_i}，庫存變化 #{@product.quantity - params[:number].to_i} => #{@product.quantity} "

		  redirect_to :back
		end
		rescue
			flash[:warning] = "操作失敗，請重新嘗試，補貨數量請填入整數"  
			redirect_to :back
	end

	#商品置頂
	def mark
		if Product.be_marked.count < 5

			product = Product.find_by(id: params[:id])
			product.mark = true
			product.save
	
			flash[:success] = "#{product.title} 已置頂"
	
			redirect_to :back
		else
			flash[:warning] = "置頂數量已滿，請先將部分產品取消置頂"
			redirect_to :back
		end		
	end

	#取消置頂
	def unmark
		product = Product.find_by(id: params[:id])
		product.mark = false
		product.save

		flash[:success] = "#{product.title} 已取消置頂"

		redirect_to :back		
	end



	private

		def product_params
			params.require(:product).permit(:title, :description, :quantity, :price, :category_name,
																			 :category_id, :nutrition_facts, :certification, :origin,
																			 :introduction, :weight, :expiration_date, :special,
																			 :special_price, photo_attributes: [:image, :id])
		end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


	def index


    @products = Product.products_are_selling.includes(:photo).order(created_at: :DESC).page(params[:page]).per(6)

		@articles = Article.order(created_at: :DESC).limit(4).select("id, title, created_at, article_img")

		@sticky_1 = Article.select("id, title, created_at, article_img, sticky").find_by(sticky: 1)
		@sticky_2 = Article.select("id, title, created_at, article_img, sticky").find_by(sticky: 2)

		@marked_product = Product.be_marked.products_are_selling.includes(:photo).order(created_at: :DESC)

		respond_to do |format|
			format.html
			format.js
		end	

	end

	def total_articles
		@articles = Article.page(params[:page]).per(10)
	end

	def show
		@product = Product.find(params[:id])
		@marked_product = Product.be_marked.products_are_selling.includes(:photo, :category).order(created_at: :DESC)
	end

	def add_to_cart
		@product = Product.find_by(id: params[:id])
		quantity = params[:quantity]

		if !current_cart.items.include?(@product)
			current_cart.add_product_to_cart(@product, quantity)
			flash[:success] = "你已成功將 #{@product.title} #{params[:quantity]}個加入購物車"
		else
			item = current_cart.quantity_plus(@product)
			flash[:success] = "#{@product.title}"
		end
			
		redirect_to :back

		rescue

    logger.error("Attempt to access invalid product #{params[:id]}")
    flash[:notice] = '商品不存在或已被刪除'
    redirect_to root_path

	end


end

app/helpers/manager/products_helper.rb
module Manager::ProductsHelper

	def render_shelf_option(product)
		if 	product.selling == true
			link_to("下架", off_shelf_manager_product_path(product), method: :post)
		else
			link_to("上架", on_shelf_manager_product_path(product), method: :post)
		end	
	end

end

app/helpers/products_helper.rb
module ProductsHelper
	# 商品數量下拉選單範圍
	def product_quantity_range(product)
		array = []
		if product.quantity > 10
			10.times do |i|
				n = i + 1
				array << [n.to_s, n]
			end
		else	
			product.quantity.times do |i|
				n = i + 1
				array << [n.to_s, n]
			end
		end	
		array	
	end

	#特價時顯示特價價格(products頁面)
	def render_price(product)
		if product.special?
			content_tag(:span, "NT$#{product.price} ", class: "", style: "text-decoration:line-through;") +
			content_tag(:span, " $#{product.special_price}", class: "red") 
		else
			content_tag(:span, "NT$#{product.price}", class: "")
		end	
	end

	#回傳真實價格
	def true_price(product)
		if product.special?
			product.special_price
		else	
			product.price
		end
	end

end

app/views/products/_article_content.html.erb
<div class=" col-md-12 modal fade" id="render_article" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title center" id="ajax-article-title">....</h4>
      </div>
      <div class="modal-body article-description" id="ajax-article-description">
        <!-- 讀取中icon -->
        <div class="center" style="padding: 60px 0;">
          <i class="fa fa-refresh fa-spin fa-3x fa-fw" id="ajax-article-loading"></i>
          <span class="sr-only">Loading...</span>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-normal" data-dismiss="modal">關閉</button>
      </div>
    </div>
  </div>
</div>

app/views/products/_articles.html.erb
<div id="articles" class="row">

	<% @articles.each do |article| %>
		<div class="article col-md-6 col-sm-12 col-xs-12 load-article" data-articleid="<%= article.id %>">
			<div class="row">
				<%= link_to "#", data: {toggle: "modal", target: "#render_article"} do %>
					<div class="col-md-5 col-xs-12 col-sm-4 article-img" style="background:url(<%= image_url(article.article_img.medium) %>)"></div>
				<% end %>				
				<div class="col-md-7 col-xs-12 col-sm-8 article-content">
					<div class="article-title"><%= link_to article.title, "#", 
						data: {toggle: "modal", target: "#render_article"}, class: "normal-link" %></div>
					<div class="article-created small gray"><%= article.created_at.to_s(:simple) %></div>
				</div>
			</div>
			<div class="clearfix"></div>
			<hr>
		</div>
	<% end %> 	
</div>


<div class="clearfix"></div>

app/views/products/_carousel.html.erb
<!-- 輪撥 -->

<div id="myCarousel" class="carousel slide"  data-ride="carousel">
    <!-- 轮播（Carousel）指标 -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>   
    <!-- 轮播（Carousel）项目 -->
    <div class="carousel-inner carousel-size">
        <div class="item active">
		  <a href=<%= @setting.carousel1_link %> >
            <%= image_tag(@setting.carousel1, alt: "First slide", class: "carousel-img" ) %>
          </a>
        </div>
        <div class="item">
          <a href=<%= @setting.carousel2_link %> >
		        <%= image_tag(@setting.carousel2, alt: "Second slide", class: "carousel-img" ) %>
          </a>              
        </div>
        <div class="item">
          <a href=<%= @setting.carousel3_link %> >
		        <%= image_tag(@setting.carousel3, alt: "Third slide", class: "carousel-img" ) %>
           </a> 
        </div>

    </div>
    <!-- 轮播（Carousel）导航 -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">
      <i class="fa fa-chevron-left" aria-hidden="true"></i>
    </a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">
      <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</div>

<!-- 輪撥測試 -->

app/views/products/_phone_carousel.html.erb
<!-- 輪撥 -->

<div id="myCarousel_phone" class="carousel slide"  data-ride="carousel">
    <!-- 轮播（Carousel）指标 -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel_phone" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel_phone" data-slide-to="1"></li>
        <li data-target="#myCarousel_phone" data-slide-to="2"></li>
    </ol>   
    <!-- 轮播（Carousel）项目 -->
    <div class="carousel-inner carousel-size_p">
        <div class="item active">
		  <a href=<%= @setting.carousel1_link_p %> >
            <%= image_tag(@setting.carousel1_p, alt: "First slide", class: "carousel-img" ) %>
          </a>
        </div>
        <div class="item">
          <a href=<%= @setting.carousel2_link_p %> >
		        <%= image_tag(@setting.carousel2_p, alt: "Second slide", class: "carousel-img" ) %>
          </a>              
        </div>
        <div class="item">
          <a href=<%= @setting.carousel3_link_p %> >
		        <%= image_tag(@setting.carousel3_p, alt: "Third slide", class: "carousel-img" ) %>
           </a> 
        </div>

    </div>
    <!-- 轮播（Carousel）导航 -->
    <a class="carousel-control left" href="#myCarousel_phone" data-slide="prev">
      <i class="fa fa-chevron-left" aria-hidden="true"></i>
    </a>
    <a class="carousel-control right" href="#myCarousel_phone" data-slide="next">
      <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
</div>

<!-- 輪撥測試 -->

app/views/products/_product_tabs.html.erb
<div class="lg-screen-margin15">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#discription" aria-controls="discription" role="tab" data-toggle="tab">產品詳情</a>
    </li>
    <li role="presentation">
      <a href="#nutrition" aria-controls="nutrition" role="tab" data-toggle="tab">產品規格</a>
    </li>
    <li role="presentation">
      <a href="#certification" aria-controls="certification" role="tab" data-toggle="tab">認證標章</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content border-no-top">
    <div role="tabpanel" class="tab-pane active" id="discription">
      <div class="article-description"><%= raw(@product.description) %></div>
    </div>
    <div role="tabpanel" class="tab-pane tab-product" id="nutrition">
      <%= image_tag(@product.nutrition_facts.url, alt: "#{@product.title}") %>
    </div>
    <div role="tabpanel" class="tab-pane tab-product" id="certification">
      <%= image_tag(@product.certification.url) %>
    </div>
  </div>

</div>

app/views/products/_sticky.html.erb
	<!-- 置頂資訊 -->
	<% if @sticky_1 && @sticky_2 %>
		<div id="top-articles-box">
			<div class="row">		
				<!-- 置頂1 -->
					<%= link_to "#", data: {toggle: "modal", target: "#render_article"}, 
					class: "white-link opacity-link" do %>
						<div class="load-article col-md-7 col-xs-12 article-1 top-articles" style="background:url(<%= image_url(@sticky_1.article_img.url) %>)" data-articleid="<%= @sticky_1.id %>">
							<span class="date"><%= @sticky_1.created_at.to_s(:zh) %></span>
							<span class="article-1-title"><%= @sticky_1.title %></span>
						</div>
					<% end %>

				<!-- 置頂2 -->
				<div class="col-md-5 col-xs-12 load-article" data-articleid="<%= @sticky_2.id %>">
					<div class="row">
						<%= link_to '#', 
						data: {toggle: "modal", target: "#render_article", articleid: "article.id"}, 
						class: "white-link opacity-link load-article" do %>
							<div class="col-md-11 col-md-offset-1 col-xs-12 article-2 top-articles" style="background:url(<%= 		image_url(@sticky_2.article_img.url) %>)">
								<span class="date"><%= @sticky_2.created_at.to_s(:zh) %></span>
								<span class="article-2-title"><%= @sticky_2.title %></span>
							</div>
						<% end %>	
				<!-- 置頂2 end -->	
						<div class="col-md-11 col-md-offset-1 col-xs-12 ">
							<%= link_to total_articles_products_path, class: "gold-link block" do %>
								<div class=" " style="animation-duration: 7s" >
									<span class="letter-spacing-1 normal">看更多資訊</span>
									<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
								</div>
							<% end %>	
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<!-- 置頂資訊end -->
	<br>

app/views/products/index.html.erb
<!-- modal必須放最前 -->
<%= render partial: 'article_content' %>

<div class="products-page for-lg">


	<!-- 輪播 -->
	<div class="hidden-xs">
		<%= render 'carousel' %>
	</div>	

	<div class="visible-xs-block">
		<%= render 'phone_carousel' %>
	</div>


	<div class="hidden hidden-box"></div>

	
	<!-- 置頂文章 -->
	<%= render 'sticky' %>


	<div class="padding-rl-40 ">
	
		<!-- 資訊 -->
		<div class="mtd-small hidden-xs" >
			<h4 class="inline-block">資訊</h4>
			<%= render 'articles' %>
		</div>
	
		<div class="">
			<h5 class="inline-bloc pull-right hidden-xs"><%= link_to total_articles_products_path, class: "gray-link" do %>
				<span>看更多</span>
				<i class="fa fa-chevron-right" aria-hidden="true"></i>
			<% end %>
			</h5>		
		</div>
		<!-- end資訊 -->
	 
		<h4 class="inline-block">商城</h4>

		<!-- 置頂商品 -->
		<div class="marked_products flex hidden-xs">
			<% @marked_product.each do |product| %>
				<div class="marked_product center">
					<%= link_to product_path(product) do %>
						<%= image_tag(product.photo.image.medium.url, 
						alt: product.title, title: product.title, class: "") %>
						<h5><%= product.title %></h5>
						<div class="center small" style="margin-top:-5px;"><%= render_price(product) %></div>
					<% end %>
				</div>
			<% end %>	
		</div>			

		
		<div class="row">	
			<!-- category -->
			<div class="categories col-md-2 col-sm-2 hidden-xs">
				<div><%= link_to "所有產品", categories_path, class: "normal-link bold" %></div>
				<hr>
				<div><%= link_to "特價商品", categories_path(on_sale: true), class: "red" %></div>
				<hr>
				<% @categories.each do |category| %>
					<div>
						<%= link_to category.name , category_path(category), class: "normal-link bold"  %>
						<hr>
					</div>
				<% end %>
			</div>

			<div class="product-items col-md-10  col-sm-10 col-xs-12">
				<h2 class="background width100"><span> 所有產品 </span></h2>
				<div id="product-delegate">
					<%= render 'categories/products' %>
				</div>
				<!-- 如果有下一頁顯示載入更多按鈕 -->
				<div style="width: 100%;">
					<% if @products.next_page %>
						<%= render_ajax_more_button(@products) %>
					<% end %>	
				</div>
				<!-- 載入更多按鈕end -->

				<!-- loading -->
					<div class="btn" id="loading" style="display:none;">
						<i class="fa fa-refresh fa-spin fa-3x fa-fw"></i>
						<span class="sr-only">Loading...</span>	
					</div>
					<script>
					$('#js-load-more').on('click', function() {
						$('#js-load-more').hide();			
						$('#loading').show();
					});
					</script>		
				<!-- loding end -->
			</div>

			<div class=" clearfix"></div>
		</div>

	</div>
</div>

<!-- 修正輪播圖寬高 -->
<%= render 'js/bootstrap_tab' %>


<!-- ajax載入文章 -->
<script>
	$('.load-article').on('click', function() {
		$.ajax({
			url: "<%= render_article_path(:json) %>",
			type: 'GET',
			datatype: "json",
			data: {id: $(this).data('articleid')},
			timeout: 10000,
			success: function(response) {
				var title = response['title']
				var description = response['description']
				$('#ajax-article-title').html(title);
				$('#ajax-article-description').html(description);
			},
			error: function() {
				$('#ajax-article-title').html('....');
				$('#ajax-article-description').html('文章載入失敗，請稍後重試');
			}
		});
	});
</script>

app/views/products/index.js.erb
$.ajax({
	url: 'products',
	timeout: 10000,
	beforeSend: function() {
		$('#js-load-more').off('click');
	},
	success: function() {
		$('#products-list').append("<%= j render 'categories/products' %>");	
	},
	complete: function() {
		$('#loading').hide();
		<% if @products.next_page %>
			$('#js-load-more').show();
			$('#js-load-more').replaceWith('<%= j render_ajax_more_button(@products) %>');

			// 重新綁定click事件
			$('#js-load-more').on('click', function() {
				$('#js-load-more').hide();
				$('#loading').show();			
			});			
		<% else %>	
			$('#js-load-more').remove();
		<% end %>
	},
	error: function() {
		$('#loading').hide();
		$('#js-load-more').show();
	}
});

app/views/products/show.html.erb
<div class="for-lg">
<div class="padding-rl-40">

	<div class="md row">
		<%= manager_link("編輯", edit_manager_product_path(@product), class: "center block m-link") %>

		<div class="col-md-12 col-xs-12 margin-td">
			<%= link_to "首頁", root_path, class: "black-link"  %>
			<i class="fa fa-angle-double-right" aria-hidden="true"></i>
			<%= link_to @product.category.name, category_path(@product.category), class: "black-link"  %>
			<i class="fa fa-angle-double-right" aria-hidden="true"></i>
			<%= @product.title %>
		</div>


		<!-- 產品圖 -->
		<div class="col-md-5 col-xs-12 margin-td border img-100 product-img">
			<%= image_tag(@product.photo.image.medium.url, alt: @product.title, title: @product.title) %>
		</div>

	
		<div class="col-md-7 col-xs-12">
			<!-- 商品名 -->
			<h3 class="flex">
				<span><%= @product.title %></span>
				<% if @product.special? %>
					<span class="smallest red border-s" style="margin-left:10px;">
						<i class="fa fa-star-half-o" aria-hidden="true"></i>
						特價中
					</span>
				<% end %>
			</h3>
			<span class="small red"><%= "單筆訂單滿#{@setting.shipping_free}免運" %></span class="small red">

			<!-- 簡述 -->


	

			<!-- 商品價格 -->
			<div class="product-price" style="position: relative;">
				<% if @product.special? %>
					<div class="smallest lighter" style="text-decoration:line-through;margin-top:-19px;">
						原價 NT$<%= @product.price %>
					</div>
				<% end %>
				<span id="product-price-nt" class="<%= 'lighter' if !@product.special? %>"> NT$</span>
				<span id="product-price-number" class="<%= 'lighter' if !@product.special? %>">
					<% if  %>
						<% @product.special? %>
							<span class=""><%= @product.special_price %></span>
					<% else %>
							<span class="" style=""><%= @product.price %></span>
					<% end %>
				</span>
			</div>


			<!-- 產地，資訊等等.. -->
			<div class="product-info row ">
				<div class="col-md-7">運費： 
					<%= "$#{@setting.shipping_cost}" %>
				</div>					
				<div class="col-md-5">保存期限： <%= @product.expiration_date %></div>
				<div class="col-md-7">重量： <%= @product.weight %></div>
				<% if !@product.origin.empty? %>
					<div class="col-md-5">產地： <%= @product.origin %></div>
				<% end %>	
			</div>
			

			<!-- 數量與購物車 -->
			<div class="row cart_and_number">
				<% if @product.quantity == 0 %>
					<div class="padding-rl pull-left">
						<span class="button-disabled ">缺貨中</span>
					</div>
					
				<% else %>

					<!-- 加入購物車form & product-delegate -->
					<div id="product-delegate">
							
							<div class="col-md-7 col-xs-6">
								<span class="black6">數量：</span>
								<div class="styled-select inline-block">
								  <%= select_tag(:quantity, options_for_select(product_quantity_range(@product))) %>
								</div>
							</div>
	
							<div class="col-md-5 col-xs-5" style="margin-top:15px;">
								<%= link_to("#", class: "button-special xs-small add_to_cart",
								data: { "product-id" => @product.id}, remote: true ) do %>
									<i class="fa fa-cart-plus fa-2x" aria-hidden="true"></i>
									<span class=""> 加入購物車</span>
								<% end %>
							</div>
	
					</div>
					<!-- product-delegate end -->
				<% end %>
			</div>
			<!-- 數量與購物車end -->
		</div>


		<!-- 商品訊息 -->
		<div class=" col-md-11 col-xs-12">
			<%= render 'product_tabs' %>
		</div>


		<h3 class="mt background col-md-11 col-xs-12"><span class="pull-left"> 商品推薦 </span></h3>
		<div class="marked_products flex col-md-11 col-xs-12">
			<% @marked_product.each do |product| %>
				<div class="marked_product  center">
					<%= link_to product_path(product) do %>
						<%= image_tag(product.photo.image.medium.url, 
						alt: product.title, title: product.title, class: "") %>
						<h5><%= product.title %></h5>
						<div class="center small" style="margin-top:-5px;"><%= render_price(product) %></div>
					<% end %>
				</div>
			<% end %>	
		</div>			

<!-- 		<div class="col-md-3 col-md-offset-1 col-xs-12 border-m">
				<p class="bold">付款方式</p>
				<p>信用卡一次付清 / ATM / WebATM / 超商代碼繳費</p>
				<p class="bold">運送方式</p>
				<p>郵寄 / 宅配 (NTD100)</p>
		</div>
 -->
		<div class=" clearfix"></div>

		<%= manager_link("編輯", edit_manager_product_path(@product), class: "center block m-link mt") %>

	</div>
</div>

</div>

app/views/products/total_articles.html.erb
<%= render partial: 'article_content' %>


<div class="padding-rl-40 mt">
	<!-- 分頁 -->
	<%= paginate @articles %>

	<%= render 'articles' %>

	<!-- 分頁 -->
	<%= paginate @articles %>	
</div>

<!-- ajax載入文章 -->
<script>
	$('.load-article').on('click', function() {
		$.ajax({
			url: "<%= render_article_path(:json) %>",
			type: 'GET',
			datatype: "json",
			data: {id: $(this).data('articleid')},
			success: function(response) {
				var title = response['title']
				var description = response['description']
				$('#ajax-article-title').html(title);
				$('#ajax-article-description').html(description);
			},
			error: function() {
				$('#ajax-article-title').html('....');
				$('#ajax-article-description').html('文章載入失敗，請稍後重試');
			}
		});
	});
</script>