config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :managers
  
  root 'products#index'
  get  'render_article' => 'ajax#render_article'
  post  'add_to_cart' => 'ajax#add_to_cart'

  post "pay2go_return"   => 'orders#pay2go_return'
  post "pay2go_notify"   => 'orders#pay2go_notify'
  post "pay2go_customer" => 'orders#pay2go_customer'

  
  post "spgateway_return"   => 'orders#spgateway_return'
  post "spgateway_notify"   => 'orders#spgateway_notify'
  post "spgateway_customer" => 'orders#spgateway_customer'

  namespace :manager do
    root to:  'core#index'
    get 'index' => 'core#index'
    get 'set_session' => 'core#set_session'
    get 'clear' => 'core#clear'
    get 'zbc' => "core#zbc"
    resources :products do
      member do
        post :off_shelf
        post :on_shelf
        post :replenish
        post :mark
        post :unmark
      end
    end    
    resources :orders do
      member do
        post :cancel
        post :shipped
        post :refund
        post :return
        post :return_fail
        get  :message_board
        get  :message_of_cancel
        post :create_message        
      end
    end
    resources :articles do
      member do
        post :sticky
        post :sticky_cancel
      end
    end    
    resources :settings
  end 

  resources :products do
    collection do
      get :total_articles
    end  
    member do 
      post :add_to_cart
    end
  end

  resources :categories, only: [:index, :show]

  resources :carts  do 
    collection do 
      get :checkout
      post :refresh
      delete :delete_cart_item
      delete :clean
    end
  end

  resources :orders  do 
    member do 
      post :realtime_return
      post :realtime_notify
      post :non_realtime_customer
      post :non_realtime_notify
      post :pay2go_cc_notify
      post :pay2go_cc_return
      post :pay2go_wa_notify
      post :pay2go_wa_return
      post :pay2go_atm_return
      post :pay2go_atm_notify
    end
  end   

  namespace :account do 
    get 'index' => 'core#index'
    get 'user_info' => 'core#user_info'
    post 'build_user_info' => 'core#build_user_info'
    resources :orders do 
      member do
        post :cancel
        post :request_return
        get  :message_board
        get  :message_of_cancel
        get  :message_of_return
        post :create_message
        get  :payment_info
      end
    end
  end

end

app/views/common/_about_us.html.erb
<!-- Modal -->
<div class=" col-md-12 modal fade" id="about_us_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title center">認識圓滿生機</h4>
      </div>
      <div class="modal-body article-description">
        <%= raw(@setting.about_us) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-normal" data-dismiss="modal">關閉</button>
      </div>
    </div>
  </div>
</div>

app/views/common/_error_messages.html.erb
<% if var.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-warning">
		抱歉，有<%= var.errors.count %>個小問題.
	</div>
	<ul>
		<% var.errors.each do |key,msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/common/_manager_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-list">
    		<i class="fa fa-bars" aria-hidden="true"></i>
			</button>
		</div>
		<div class="collapse navbar-collapse" id="nav-list">
			<ul class="nav navbar-nav">
			  <li>
			  	<%= link_to root_path do %>
			  		<i class="fa fa-home fa-lg" aria-hidden="true"></i>
			  		首頁
			  	<% end %>	
			  </li>
			  <li>
			  	<%= link_to manager_index_path do %>
			  		<i class="fa fa-list-alt fa-lg" aria-hidden="true"></i>
			  		訂單管理
			  	<% end %>	
			  </li>
			  <li>
			  	<%= link_to manager_products_path do %>
			  		<i class="fa fa-list-ol fa-lg" aria-hidden="true"></i>
			  		商品管理
			  	<% end %>	
			  </li>
			  <li>
			  	<%= link_to manager_articles_path do %>
			  		<i class="fa fa-book fa-lg" aria-hidden="true"></i>
			  		文章列表
			  	<% end %>	
			  </li>
			  <li>
			  	<%= link_to  new_manager_article_path do %>
			  		<i class="fa fa-paint-brush fa-lg" aria-hidden="true"></i>
			  		發表文章
			  	<% end %>	
			  </li>
			  <li class="product-on-shelf">
			  	<%= link_to  new_manager_product_path do %>
			  		<i class="fa fa-plus-circle fa-lg" aria-hidden="true"></i>
			  		新增商品
			  	<% end %>	
			  </li>
			  <li>
			  	<%= link_to manager_settings_path do %>
			  		<i class="fa fa-cog fa-lg" aria-hidden="true"></i>
			  		設定
			  	<% end %>	
			  </li>			  
			</ul>
			<ul class="nav navbar-nav navbar-right nav-list">
			  <li><%= link_to("登出", destroy_manager_session_path, method: :delete) %></li>
			</ul>
		</div>
	</div>	
</nav>	

app/views/common/_navbar.html.erb
<%= render 'common/about_us' %>
<%= render 'common/q_and_a' %>

<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navar-header">

			<div class="flex-box visible-xs-block">
				<div class="navbar-toggle lines-button x" data-toggle="collapse" data-target="#nav-list">
					<span class="lines"></span>
				</div>
			</div>	


 			<%= link_to root_path, class: "navbar-brand" do %>	
				<%= image_tag("logo4-01.png", class: "brand", alt: "圓滿生機") %>
			<% end %>	

			<!-- 手機購物車 -->
			<span class="visible-xs nav-cart ajax-cart">
				<%= link_to carts_path, class: "" do %>
					<i class="fa fa-shopping-cart gray2"></i>
					<span class="as" style="padding:0;">
						<span style="animation-duration: 3s"><%= render_cart_items_count(current_cart) %></span> 
					</span> 
				<% end %>	
			</span>
			<!-- end手機購物車 -->
		</div>

		

		<div class="collapse navbar-collapse" id="nav-list">

			<!-- 左nav -->
			<ul class="nav navbar-nav navbar-left center">
				<li>
					<%= link_to "認識圓滿生機", "#", data: {toggle: "modal", target: "#about_us_modal"}  %>
				</li>
				<!-- 下拉分類 -->
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						商品 / 類別 <span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to "所有產品", categories_path, class: "normal-link bold" %></li>
						<li><%= link_to "特價商品", categories_path(on_sale: true), class: "normal-link bold" %></li>
						<% @categories.each do |category| %>
							<li><%= link_to category.name , category_path(category) %></li>
						<% end %>
					</ul>
				</li>
				<!-- 分類end -->
				
				<li class="hidden-sm" ><%= link_to "文章推薦", total_articles_products_path %></li>

				<li><%= link_to "購物須知", "#", data: {toggle: "modal", target: "#q_and_a_modal"}  %></li>
				<li class="hidden-xs hidden-sm">
					<%= link_to "#" do %>
						<i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#3c5a9a;"></i>
					<% end %>
				</li>
			</ul>

			<!-- 右nav -->
			<ul class="nav navbar-nav navbar-right center">
				<!-- 購物車 -->
				<li class="" id="cart-box">
					<%= link_to carts_path, class: "ajax-cart" do %>
						<i class="fa fa-shopping-cart gray2"></i>
						購物車
						<span class="as"> 
							( <span style="animation-duration: 3s"><%= render_cart_items_count(current_cart) %></span> ) 
						</span> 
					<% end %>	
				</li>
				<!-- end購物車 -->
				<% if user_signed_in? %>
					<li>
						<%= link_to account_index_path  do %>
							<i class="fa fa-user" aria-hidden="true"></i> 會員中心
						<% end %>	
					</li>
					<li>
						<%= link_to destroy_user_session_path, method: :delete do %>
							<i class="fa fa-sign-out" aria-hidden="true"></i> 登出
						<% end %>	
					</li>
				<% else %>
					<li><%= link_to "會員登入", new_user_session_path %></li>
					<li><%= link_to "註冊", new_user_registration_path  %></li>
				<% end %>	
			</ul>
		</div>
	</div>	
</nav>	

app/views/common/_q_and_a.html.erb
<!-- Modal -->
<div class=" col-md-12 modal fade" id="q_and_a_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title center">Q ＆ A</h4>
      </div>
      <div class="modal-body article-description">
        <%= raw(@setting.q_and_a) %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-normal" data-dismiss="modal">關閉</button>
      </div>
    </div>
  </div>
</div>